// ==UserScript==
// @name         Tilewars
// @namespace    http://tileman.io/
// @version      0.1
// @description  design update. thats it. that simpl. ok.
// @author       ijka5844
// @match        http://tileman.io/
// @grant        none
// ==/UserScript==
document.write( '<style>\n' );
document.write( '@import url(\'https://fonts.googleapis.com/css2?family=DM+Mono&display=swap\');\n' );
document.write( '* {\n' );
document.write( '   font-family: \'DM Mono\', monospace; \n' );
document.write( '   cursor: url(\'https://cdn.glitch.com/d7abfe5c-405d-44c8-a41b-adbe5b69314d%2Fnormal-select-blue.cur?v=1593278901199\'), auto;	\n' );
document.write( '}\n' );
document.write( 'body {\n' );
document.write( '	background-color: #1e1e1e;\n' );
document.write( '	color: #fff;\n' );
document.write( '	margin: 0;\n' );
document.write( '	padding: 10px;\n' );
document.write( '	background: fixed repeat center/100% url(../images/tileman.io-tileman-blur-black.png) #1E1E1E;\n' );
document.write( '	touch-action: manipulation\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( 'body>:not(#intro):not(#game) a img {\n' );
document.write( '	display: none!important;\n' );
document.write( '	left: 0;\n' );
document.write( '	position: absolute!important;\n' );
document.write( '	pointer-events: none;\n' );
document.write( '	opacity: 0;\n' );
document.write( '	visibility: hidden\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( 'table {\n' );
document.write( '	border-collapse: collapse;\n' );
document.write( '	border: 1px solid #fff;\n' );
document.write( '	display: inline-table;\n' );
document.write( '	background-color: rgba(128, 128, 128, .5)\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( 'th,\n' );
document.write( 'td {\n' );
document.write( '	padding: 10px;\n' );
document.write( '	border-color: #fff\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( 'a {\n' );
document.write( '	text-decoration: none;\n' );
document.write( '	color: #55f\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( 'a:hover {\n' );
document.write( '	text-decoration: underline\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( 'hr {\n' );
document.write( '	height: 1px;\n' );
document.write( '	border: 0;\n' );
document.write( '	background-color: #fff;\n' );
document.write( '	max-width: 500px;\n' );
document.write( '	margin: 20px auto\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( 'p {\n' );
document.write( '	max-width: 800px;\n' );
document.write( '	margin-left: auto;\n' );
document.write( '	margin-right: auto\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( 'ul {\n' );
document.write( '	display: table;\n' );
document.write( '	margin-left: auto;\n' );
document.write( '	margin-right: auto\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( 'li {\n' );
document.write( '	text-align: left\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( 'small {\n' );
document.write( '	color: #999\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( 'label {\n' );
document.write( '	-moz-user-select: none;\n' );
document.write( '	-webkit-user-select: none;\n' );
document.write( '	-ms-user-select: none;\n' );
document.write( '	user-select: none\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( 'body>iframe {\n' );
document.write( '	display: none!important\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.hidden:after {\n' );
document.write( '	content: attr(data-txt)\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.good {\n' );
document.write( '	color: #7fff00\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.bad {\n' );
document.write( '	color: #ff4500\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.colorbox {\n' );
document.write( '	width: 50px;\n' );
document.write( '	height: 50px;\n' );
document.write( '	display: block\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#intro {\n' );
document.write( '	text-align: center\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( 'h1 {\n' );
document.write( 'font-family: \"Lucida Console\", Monaco, monospace;\n' );
document.write( 'font-size: 26px;\n' );
document.write( 'letter-spacing: 1.8px;\n' );
document.write( 'word-spacing: 0.8px;\n' );
document.write( 'color: #FFFFFF;\n' );
document.write( 'font-weight: normal;\n' );
document.write( 'text-decoration: none;\n' );
document.write( 'font-style: normal;\n' );
document.write( 'font-variant: normal;\n' );
document.write( 'text-transform: none;\n' );
document.write( 'text-shadow: 2px 2px #00FFFF;\n' );
document.write( '	margin: calc(30px + 0.17em) 0\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.bottom-div {\n' );
document.write( '	background-color: rgba(90, 90, 90, .8);\n' );
document.write( '	position: fixed;\n' );
document.write( '	bottom: 0;\n' );
document.write( '	left: 0;\n' );
document.write( '	right: 0;\n' );
document.write( '	padding: 5px;\n' );
document.write( '	font-size: 1.2em\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#rateclose {}\n' );
document.write( '\n' );
document.write( '#rateclose {\n' );
document.write( '	background-color: #ff8c00;\n' );
document.write( '	color: #fff;\n' );
document.write( '	border: 1px solid rgba(0, 0, 0, .3);\n' );
document.write( '	padding: 10px;\n' );
document.write( '	box-sizing: border-box;\n' );
document.write( '	margin: 5px\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#rateclose:hover {\n' );
document.write( '	background-color: #ffa333\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( 'div.lb h3 {\n' );
document.write( '	position: relative;\n' );
document.write( '	top: 40px\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( 'a.lb {\n' );
document.write( '	position: fixed;\n' );
document.write( '	display: none\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( 'div.lb {\n' );
document.write( '	display: none\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( 'a.lb.selected+div.lb {\n' );
document.write( '	display: block\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( 'a.lb:target+div.lb {\n' );
document.write( '	display: block\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.abcd {\n' );
document.write( '	display: inline-block;\n' );
document.write( '	margin: 5px 30px\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.abcd td+td {\n' );
document.write( '	min-width: 300px;\n' );
document.write( '	max-width: 400px;\n' );
document.write( '	overflow: hidden;\n' );
document.write( '	text-overflow: ellipsis\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.abcd td+td+td {\n' );
document.write( '	min-width: 100px\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#links {\n' );
document.write( '	position: absolute;\n' );
document.write( '	right: 5px;\n' );
document.write( '	top: 0\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#links a {\n' );
document.write( '	padding-top: 5px;\n' );
document.write( '	display: inline-block;\n' );
document.write( '	padding-bottom: 22px\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#social {\n' );
document.write( '	position: fixed;\n' );
document.write( '	left: 5px;\n' );
document.write( '	bottom: 5px\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#social a {\n' );
document.write( '	color: #fff;\n' );
document.write( '	background: green;\n' );
document.write( '	border-radiuss: 5px;\n' );
document.write( '	bbox-shadow: 0 -10px red;\n' );
document.write( '	padding: 5px;\n' );
document.write( '	font-weight: 700;\n' );
document.write( '	opacity: .5;\n' );
document.write( '	background-size: 20px;\n' );
document.write( '	background-repeat: no-repeat;\n' );
document.write( '	background-position: 0 center;\n' );
document.write( '	display: inline-block\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#social a:hover {\n' );
document.write( '	text-decoration: none;\n' );
document.write( '	opacity: 1\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#social a.tw-link {\n' );
document.write( '	background-color: #1b95e0;\n' );
document.write( '	background-image: url(../images/tileman.io-twitter.png);\n' );
document.write( '	padding-left: 20px\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#social a.fa {\n' );
document.write( '	background: #3b5998;\n' );
document.write( '	background-image: url(../images/tileman.io-fb.png);\n' );
document.write( '	background-size: 20px;\n' );
document.write( '	background-repeat: no-repeat;\n' );
document.write( '	background-position: 0 center;\n' );
document.write( '	padding-left: 20px\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#social a.dis-link {\n' );
document.write( '	background-color: #7289da;\n' );
document.write( '	background-image: url(../images/tileman.io-discord.png);\n' );
document.write( '	padding-left: 20px\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#social a.red-link {\n' );
document.write( '	background-color: #ff4500;\n' );
document.write( '	background-image: url(../images/tileman.io-re.png);\n' );
document.write( '	padding-left: 20px\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.region {\n' );
document.write( '	background-color: #ff00fb;\n' );
document.write( '	color: #fff;\n' );
document.write( '	border: 0;\n' );
document.write( '	font-size: 1em;\n' );
document.write( '	padding: 6px;\n' );
document.write( '	margin: 5px 4px;\n' );
document.write( '	wwidth: 4.8em;\n' );
document.write( '	box-sizing: border-box;\n' );
document.write( '	outline: 0;\n' );
document.write( '	font-size: .8em\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.region:hover {\n' );
document.write( '	background-color: #ff52fc\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.region.sel {\n' );
document.write( '	background-color: #ff1fe9\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.mode {\n' );
document.write( '	background-color: #2f00ff;\n' );
document.write( '	color: #fff;\n' );
document.write( '	border: 0;\n' );
document.write( '	font-size: 1em;\n' );
document.write( '	padding: 8px;\n' );
document.write( '	margin: 5px;\n' );
document.write( '	wwidth: 4.8em;\n' );
document.write( '	box-sizing: border-box;\n' );
document.write( '	outline: 0\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.mode:hover {\n' );
document.write( '	background-color: #2800d9\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.mode.sel {\n' );
document.write( '	background-color: #4014ff\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#play {\n' );
document.write( '	background-color: #00ff88;\n' );
document.write( '	color: #000000;\n' );
document.write( '	border: 0;\n' );
document.write( '  font-family: \'DM Mono\', monospace;\n' );
document.write( '	font-size: 25px;\n' );
document.write( '	padding: 10px;\n' );
document.write( '	width: 4.8em;\n' );
document.write( '	box-sizing: border-box\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#play:hover {\n' );
document.write( '	background-color: #00ffcc\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#play.loading:after {\n' );
document.write( '	background-image: url(../images/tileman.io-loading.gif);\n' );
document.write( '	background-size: 1em 1em;\n' );
document.write( '	background-position: center;\n' );
document.write( '	background-repeat: no-repeat;\n' );
document.write( '	width: 1em;\n' );
document.write( '	height: .7em;\n' );
document.write( '	content: \"\";\n' );
document.write( '	display: inline-block\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#nick {\n' );
document.write( '	border: 0;\n' );
document.write( '	font-size: 1.25em;\n' );
document.write( '	padding: 10px;\n' );
document.write( '	width: 12em;\n' );
document.write( '	box-sizing: border-box;\n' );
document.write( '	margin-bottom: .4em\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#mode {\n' );
document.write( '	border: 0;\n' );
document.write( '	font-size: 1.25em;\n' );
document.write( '	margin: .4em 0;\n' );
document.write( '	padding: 10px 4px;\n' );
document.write( '	width: 8.15em;\n' );
document.write( '	box-sizing: border-box\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#region {\n' );
document.write( '	border: 0;\n' );
document.write( '	font-size: 1.25em;\n' );
document.write( '	margin: .4em 0;\n' );
document.write( '	padding: 10px 4px;\n' );
document.write( '	width: 3.6em;\n' );
document.write( '	box-sizing: border-box;\n' );
document.write( '	margin-right: .25em\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#info {\n' );
document.write( '	border: 1px solid #900;\n' );
document.write( '	bbackground-color: #7fffd4;\n' );
document.write( '	color: red;\n' );
document.write( '	max-width: 400px;\n' );
document.write( '	margin: 15px auto;\n' );
document.write( '	padding: 5px\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#info:empty {\n' );
document.write( '	display: none\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#info2 {\n' );
document.write( '	margin-top: 0;\n' );
document.write( '	-moz-user-select: none;\n' );
document.write( '	-webkit-user-select: none;\n' );
document.write( '	-ms-user-select: none;\n' );
document.write( '	user-select: none\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#info2 i {\n' );
document.write( '	display: inline-block;\n' );
document.write( '	max-width: 200px;\n' );
document.write( '	white-space: nowrap;\n' );
document.write( '	overflow: hidden;\n' );
document.write( '	vertical-align: bottom;\n' );
document.write( '	padding: 0 2px\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#game {\n' );
document.write( '	font-weight: 700;\n' );
document.write( '	font-family: arial;\n' );
document.write( '	-moz-user-select: none;\n' );
document.write( '	-webkit-user-select: none;\n' );
document.write( '	-ms-user-select: none;\n' );
document.write( '	user-select: none;\n' );
document.write( '	touch-action: none;\n' );
document.write( '	background-color: #000\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#canvas {\n' );
document.write( '	position: fixed;\n' );
document.write( '	top: 0;\n' );
document.write( '	left: 0;\n' );
document.write( '	bottom: 0;\n' );
document.write( '	right: 0;\n' );
document.write( '	margin: auto\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#minimap {\n' );
document.write( '	background-color: rgba(200, 250, 250, .4);\n' );
document.write( '	position: fixed;\n' );
document.write( '	top: 5px;\n' );
document.write( '	left: 5px;\n' );
document.write( '	width: 105px;\n' );
document.write( '	height: 105px;\n' );
document.write( '	overflow: hidden\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#minimap_player {\n' );
document.write( '	position: absolute;\n' );
document.write( '	top: 0;\n' );
document.write( '	left: 0;\n' );
document.write( '	width: 10px;\n' );
document.write( '	height: 10px;\n' );
document.write( '	background-color: #323232;\n' );
document.write( '	border-radius: 5px\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.corner {\n' );
document.write( '	position: fixed;\n' );
document.write( '	text-align: right;\n' );
document.write( '	text-shadow: -.0625em -.0625em 0 #000, .0625em -.0625em 0 #000, -.0625em .0625em 0 #000, .0625em .0625em 0 #000\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.corner_left {\n' );
document.write( '	position: fixed;\n' );
document.write( '	text-shadow: -.0625em -.0625em 0 #000, .0625em -.0625em 0 #000, -.0625em .0625em 0 #000, .0625em .0625em 0 #000\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#leftbottom {\n' );
document.write( '	bottom: 5px;\n' );
document.write( '	left: 5px;\n' );
document.write( '	transform-origin: bottom left\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#blink_buttons {\n' );
document.write( '	padding: 10px;\n' );
document.write( '	margin-left: -10px;\n' );
document.write( '	display: none\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#blink_buttons button {\n' );
document.write( '	background-color: transparent;\n' );
document.write( '	border: 0;\n' );
document.write( '	color: #fff;\n' );
document.write( '	width: 50px;\n' );
document.write( '	height: 50px;\n' );
document.write( '	padding: 0;\n' );
document.write( '	vertical-align: middle;\n' );
document.write( '	font-size: 20px;\n' );
document.write( '	font-weight: 700;\n' );
document.write( '	line-height: .1;\n' );
document.write( '	outline: 0;\n' );
document.write( '	opacity: .5\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#blink_buttons button:active {\n' );
document.write( '	opacity: 1\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#blink_buttons button+button {\n' );
document.write( '	margin-left: 10px\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#blink_buttons button img {\n' );
document.write( '	width: 20px\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(orientation:portrait) {\n' );
document.write( '	#blink_buttons button {\n' );
document.write( '		display: block\n' );
document.write( '	}\n' );
document.write( '	#blink_buttons button+button {\n' );
document.write( '		margin-left: 0;\n' );
document.write( '		margin-top: 10px\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#player_stats {\n' );
document.write( '	width: 12.25em\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#performance_stats {\n' );
document.write( '	bottom: 8px;\n' );
document.write( '	right: 8px;\n' );
document.write( '	transform-origin: bottom right;\n' );
document.write( '	font-size: .9em\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#timer {\n' );
document.write( '	font-size: 2em;\n' );
document.write( '	bottom: 8px;\n' );
document.write( '	left: 50%;\n' );
document.write( '	transform: translateX(-50%)\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#leaderboard {\n' );
document.write( '	top: 5px;\n' );
document.write( '	right: 5px;\n' );
document.write( '	transform-origin: top right\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#leaders {\n' );
document.write( '	counter-reset: li;\n' );
document.write( '	list-style-type: none;\n' );
document.write( '	margin: 0;\n' );
document.write( '	padding-left: 1.75em\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#leaders li {\n' );
document.write( '	position: relative;\n' );
document.write( '	text-align: right;\n' );
document.write( '	white-space: nowrap\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#leaders li:before {\n' );
document.write( '	content: counter(li)\'.\';\n' );
document.write( '	counter-increment: li;\n' );
document.write( '	position: absolute;\n' );
document.write( '	right: 100%;\n' );
document.write( '	margin-right: .5em\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#leaders .nick {\n' );
document.write( '	display: inline-block;\n' );
document.write( '	width: 11em;\n' );
document.write( '	white-space: nowrap;\n' );
document.write( '	overflow: hidden;\n' );
document.write( '	text-align: left;\n' );
document.write( '	max-height: 2.25em;\n' );
document.write( '	padding-left: 1px;\n' );
document.write( '	margin-left: -1px\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#leaders .nick:empty {\n' );
document.write( '	width: 0\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#leaders .score {\n' );
document.write( '	display: inline-block;\n' );
document.write( '	width: 4em;\n' );
document.write( '	overflow: hidden;\n' );
document.write( '	padding-right: 1px\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#performance_stats div>span+span,\n' );
document.write( '#player_stats div>span+span {\n' );
document.write( '	display: inline-block\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#player_stats,\n' );
document.write( '#performance_stats {\n' );
document.write( '	white-space: nowrap\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#performance_stats .anim {\n' );
document.write( '	opacity: 0;\n' );
document.write( '	transition: opacity 1s;\n' );
document.write( '	transition-delay: 5s\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.stat_name {\n' );
document.write( '	display: inline-block;\n' );
document.write( '	width: 3.75em;\n' );
document.write( '	text-align: left\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#player_stats div>span+span {\n' );
document.write( '	text-align: right;\n' );
document.write( '	width: 8.5em\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#performance_stats div>span+span {\n' );
document.write( '	min-width: 3em\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#player_name {\n' );
document.write( '	overflow: hidden;\n' );
document.write( '	white-space: nowrap\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#captured {\n' );
document.write( '	transition: color 3s\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#captured.ste {\n' );
document.write( '	color: red;\n' );
document.write( '	transition: color 0s\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#kills {\n' );
document.write( '	transition: color 5s\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#kills.plus {\n' );
document.write( '	color: gold;\n' );
document.write( '	transition: color 0s\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#player_stats .plusscore {\n' );
document.write( '	width: auto;\n' );
document.write( '	margin-left: 20px;\n' );
document.write( '	font-size: 1em;\n' );
document.write( '	position: absolute\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.plusscore>span {\n' );
document.write( '	transform: scale(1.3);\n' );
document.write( '	display: inline-block;\n' );
document.write( '	margin-left: 1px\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.plusscore .anim {\n' );
document.write( '	opacity: 0;\n' );
document.write( '	transition: opacity 1s ease 3s, transform .2s;\n' );
document.write( '	transform: scale(1)\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.plusscore .minus {\n' );
document.write( '	color: red\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#captplus {\n' );
document.write( '	font-size: .8em\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#title {\n' );
document.write( '	position: fixed;\n' );
document.write( '	top: 20px;\n' );
document.write( '	left: 50%;\n' );
document.write( '	transform: translateX(-50%);\n' );
document.write( '	text-align: center;\n' );
document.write( '	opacity: 1\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#title.anim {\n' );
document.write( '	opacity: 0;\n' );
document.write( '	transition: opacity 1s;\n' );
document.write( '	transition-delay: 3s\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#player_stats,\n' );
document.write( '#leaderboard,\n' );
document.write( '#title {\n' );
document.write( '	background-color: rgba(0, 0, 0, .2);\n' );
document.write( '	padding: .5em\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#game h3 {\n' );
document.write( '	text-align: center;\n' );
document.write( '	margin: .25em 0\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#touch {\n' );
document.write( '	display: none\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#touch>div {\n' );
document.write( '	background-color: rgba(255, 255, 255, .1);\n' );
document.write( '	position: fixed;\n' );
document.write( '	height: 25vmin;\n' );
document.write( '	width: 25vmin;\n' );
document.write( '	border-radius: 5vmin;\n' );
document.write( '	border: 1px solid #fff;\n' );
document.write( '	opacity: .9;\n' );
document.write( '	left: 50%;\n' );
document.write( '	top: 50%\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#touch>div:active {\n' );
document.write( '	opacity: 1;\n' );
document.write( '	background-color: rgba(255, 255, 255, .3)\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#left {\n' );
document.write( '	transform: translate(-180%, -50%)\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#right {\n' );
document.write( '	transform: translate(80%, -50%)\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#up {\n' );
document.write( '	transform: translate(-50%, -180%)\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#down {\n' );
document.write( '	transform: translate(-50%, 80%)\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#pause {\n' );
document.write( '	transform: translate(-50%, -50%);\n' );
document.write( '	opacity: .1\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#overlay {\n' );
document.write( '	background-color: rgba(0, 0, 0, .4);\n' );
document.write( '	position: fixed;\n' );
document.write( '	top: 0;\n' );
document.write( '	bottom: 0;\n' );
document.write( '	left: 0;\n' );
document.write( '	right: 0\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#after {\n' );
document.write( '	background-color: transparent;\n' );
document.write( '	position: fixed;\n' );
document.write( '	margin: auto;\n' );
document.write( '	top: 50%;\n' );
document.write( '	left: 50%;\n' );
document.write( '	transform: translate(-50%, -50%);\n' );
document.write( '	overflow: auto;\n' );
document.write( '	max-height: 100%;\n' );
document.write( '	text-align: center;\n' );
document.write( '	touch-action: manipulation;\n' );
document.write( '	white-space: nowrap\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.spectating {\n' );
document.write( '	visibility: hidden;\n' );
document.write( '	overflow: hidden\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#after.spectating>#qwerty2>* {\n' );
document.write( '	display: none!important\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#after.spectating>.buttons {\n' );
document.write( '	visibility: visible\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#local_score2 {\n' );
document.write( '	background-color: rgba(79, 79, 79, .8);\n' );
document.write( '	text-align: centerr;\n' );
document.write( '	max-height: 50%;\n' );
document.write( '	displayy: table\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#local_score2 tdd:first-of-type {\n' );
document.write( '	text-align: left\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#local_score {\n' );
document.write( '	background-color: rgba(128, 128, 128, .5);\n' );
document.write( '	position: absolute;\n' );
document.write( '	top: 190px;\n' );
document.write( '	left: 10px;\n' );
document.write( '	wwidth: 200px;\n' );
document.write( '	text-align: center\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.high {\n' );
document.write( '	color: red;\n' );
document.write( '	border-color: #fff\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.buttons {\n' );
document.write( '	text-align: centerr\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.buttons button {\n' );
document.write( '	background-color: #ff8c00;\n' );
document.write( '	color: #fff;\n' );
document.write( '	border: 1px solid rgba(0, 0, 0, .3);\n' );
document.write( '	font-size: 1.25em;\n' );
document.write( '	padding: 10px;\n' );
document.write( '	box-sizing: border-box;\n' );
document.write( '	margin: 15px 5px\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '.buttons button:hover {\n' );
document.write( '	background-color: #ffa333\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#after.spectating>.buttons button {\n' );
document.write( '	opacity: 0;\n' );
document.write( '	transition: opacity 1s, visibility 1s;\n' );
document.write( '	transition-delay: 1s;\n' );
document.write( '	visibility: hidden\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#after.spectating2>.buttons button {\n' );
document.write( '	opacity: .7;\n' );
document.write( '	transition: opacity 0s, visibility 0s;\n' );
document.write( '	visibility: visible\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#qwerty2 {\n' );
document.write( '	bbackground-color: #fff;\n' );
document.write( '	width: 300px;\n' );
document.write( '	height: 250px;\n' );
document.write( '	margin: 0 auto;\n' );
document.write( '	margin-top: 5px;\n' );
document.write( '	display: inline-block;\n' );
document.write( '	overflow: hidden\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#qwerty2:hover {\n' );
document.write( '	visibility: visible\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(max-width:22em),\n' );
document.write( '(max-height:40em) {\n' );
document.write( '	#after {\n' );
document.write( '		font-size: .8em\n' );
document.write( '	}\n' );
document.write( '	#qwerty2 {\n' );
document.write( '		width: 240px;\n' );
document.write( '		height: 200px\n' );
document.write( '	}\n' );
document.write( '	#qwerty2>* {\n' );
document.write( '		transform: scale(.8);\n' );
document.write( '		transform-origin: top left\n' );
document.write( '	}\n' );
document.write( '	#after th,\n' );
document.write( '	#after td,\n' );
document.write( '	.buttons button {\n' );
document.write( '		padding: 8px\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(max-width:18em),\n' );
document.write( '(max-height:32em) {\n' );
document.write( '	#after {\n' );
document.write( '		font-size: .5em\n' );
document.write( '	}\n' );
document.write( '	#qwerty2 {\n' );
document.write( '		width: 150px;\n' );
document.write( '		height: 125px\n' );
document.write( '	}\n' );
document.write( '	#qwerty2>* {\n' );
document.write( '		transform: scale(.5)\n' );
document.write( '	}\n' );
document.write( '	#after th,\n' );
document.write( '	#after td,\n' );
document.write( '	.buttons button {\n' );
document.write( '		padding: 5px\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#playq {\n' );
document.write( '	position: relative;\n' );
document.write( '	height: 250px;\n' );
document.write( '	bbackground-color: #000;\n' );
document.write( '	display: table;\n' );
document.write( '	width: 100%;\n' );
document.write( '	font-size: 1em;\n' );
document.write( '	margin: 30px auto\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#playform {\n' );
document.write( '	bbackground-color: silver;\n' );
document.write( '	display: table-cell;\n' );
document.write( '	vertical-align: middle\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#qwerty1 {\n' );
document.write( '	cursorr: pointer;\n' );
document.write( '	background-color: rgba(255, 255, 155, .89);\n' );
document.write( '	width: 300px;\n' );
document.write( '	height: 250px;\n' );
document.write( '	margin: auto 50px;\n' );
document.write( '	display: inline-block;\n' );
document.write( '	overflow: hidden;\n' );
document.write( '	visibility: hidden;\n' );
document.write( '	position: absolute;\n' );
document.write( '	top: 0;\n' );
document.write( '	bottom: 0;\n' );
document.write( '	right: 50%;\n' );
document.write( '	transform: translateX(-7.5em);\n' );
document.write( '	-webkit-transform: translateX(-7.5em)\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '#qwerty1>* {\n' );
document.write( '	transform-origin: center right;\n' );
document.write( '	visibility: visible\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(max-width:62em) {\n' );
document.write( '	#qwerty1>* {\n' );
document.write( '		transform: scale(.9)\n' );
document.write( '	}\n' );
document.write( '	#playq {\n' );
document.write( '		height: 225px\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(max-width:57em) {\n' );
document.write( '	#qwerty1>* {\n' );
document.write( '		transform: scale(.8)\n' );
document.write( '	}\n' );
document.write( '	#playq {\n' );
document.write( '		height: 200px\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(max-width:53em) {\n' );
document.write( '	#playq {\n' );
document.write( '		font-size: 1em\n' );
document.write( '	}\n' );
document.write( '	#qwerty1 {\n' );
document.write( '		margin: auto 32px\n' );
document.write( '	}\n' );
document.write( '	#qwerty1>* {\n' );
document.write( '		transform: scale(.7)\n' );
document.write( '	}\n' );
document.write( '	#playq {\n' );
document.write( '		height: 175px\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(max-width:47em) {\n' );
document.write( '	#playq {\n' );
document.write( '		font-size: .9em\n' );
document.write( '	}\n' );
document.write( '	#qwerty1 {\n' );
document.write( '		margin: auto 32px\n' );
document.write( '	}\n' );
document.write( '	#qwerty1>* {\n' );
document.write( '		transform: scale(.6)\n' );
document.write( '	}\n' );
document.write( '	h1 {\n' );
document.write( '		font-size: 3.5em\n' );
document.write( '	}\n' );
document.write( '	p {\n' );
document.write( '		font-size: .9em\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(max-width:40em) {\n' );
document.write( '	#qwerty1>* {\n' );
document.write( '		transform: scale(.5)\n' );
document.write( '	}\n' );
document.write( '	#qwerty1 {\n' );
document.write( '		margin: auto 20px\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(max-width:35em) {\n' );
document.write( '	#qwerty1 {\n' );
document.write( '		position: static;\n' );
document.write( '		margin: 0;\n' );
document.write( '		margin-top: 30px;\n' );
document.write( '		transform: none\n' );
document.write( '	}\n' );
document.write( '	#qwerty1>* {\n' );
document.write( '		transform: none;\n' );
document.write( '		margin: 0\n' );
document.write( '	}\n' );
document.write( '	#playform,\n' );
document.write( '	#playq {\n' );
document.write( '		display: block;\n' );
document.write( '		height: auto\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(max-width:19em) {\n' );
document.write( '	h1 {\n' );
document.write( '		font-size: 17vw\n' );
document.write( '	}\n' );
document.write( '	#playq {\n' );
document.write( '		font-size: .7em\n' );
document.write( '	}\n' );
document.write( '	#nick,\n' );
document.write( '	#region,\n' );
document.write( '	#mode,\n' );
document.write( '	#play {\n' );
document.write( '		max-width: 100%;\n' );
document.write( '		font-size: 1.25em;\n' );
document.write( '		width: 12em;\n' );
document.write( '		margin: .2em 0\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(max-width:21em) {\n' );
document.write( '	#qwerty1 {\n' );
document.write( '		width: 240px;\n' );
document.write( '		height: 200px\n' );
document.write( '	}\n' );
document.write( '	#qwerty1>* {\n' );
document.write( '		transform: scale(.8);\n' );
document.write( '		transform-origin: top left\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(max-width:17em) {\n' );
document.write( '	#qwerty1 {\n' );
document.write( '		width: 150px;\n' );
document.write( '		height: 125px\n' );
document.write( '	}\n' );
document.write( '	#qwerty1>* {\n' );
document.write( '		transform: scale(.5)\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(max-width:22em) {\n' );
document.write( '	#social a {\n' );
document.write( '		box-sizing: border-box;\n' );
document.write( '		display: block;\n' );
document.write( '		margin: auto;\n' );
document.write( '		width: 8em;\n' );
document.write( '		max-width: 100%;\n' );
document.write( '		margin-bottom: 5px\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(max-width:1000px) {\n' );
document.write( '	#local_score {\n' );
document.write( '		position: static;\n' );
document.write( '		margin-top: 30px\n' );
document.write( '	}\n' );
document.write( '	#social {\n' );
document.write( '		position: static;\n' );
document.write( '		margin-top: 30px\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(max-width:950px) {}\n' );
document.write( '\n' );
document.write( '@media(max-width:750px) {\n' );
document.write( '	h1 {\n' );
document.write( '		margin-top: 5px;\n' );
document.write( '		margin-bottom: 25px\n' );
document.write( '	}\n' );
document.write( '	#links {\n' );
document.write( '		position: static\n' );
document.write( '	}\n' );
document.write( '	#links a {\n' );
document.write( '		padding: 0\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(max-width:50em) {\n' );
document.write( '	#leaders .nick {\n' );
document.write( '		width: 10em\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(max-width:60em),\n' );
document.write( '(max-height:40em) {\n' );
document.write( '	#game {\n' );
document.write( '		font-size: .9em\n' );
document.write( '	}\n' );
document.write( '	#leaders .nick {\n' );
document.write( '		width: 10em\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(max-width:55em),\n' );
document.write( '(max-height:30em) {\n' );
document.write( '	#game {\n' );
document.write( '		font-size: .8em\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(max-width:50em),\n' );
document.write( '(max-height:25em) {\n' );
document.write( '	#game {\n' );
document.write( '		font-size: .7em\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(max-width:45em),\n' );
document.write( '(max-height:20em) {\n' );
document.write( '	#game {\n' );
document.write( '		font-size: .6em\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(max-width:40em),\n' );
document.write( '(max-height:15em) {\n' );
document.write( '	#game {\n' );
document.write( '		font-size: .5em\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '@media(max-width:35em),\n' );
document.write( '(max-height:9em) {\n' );
document.write( '	#game {\n' );
document.write( '		font-size: 3vmin\n' );
document.write( '	}\n' );
document.write( '}\n' );
document.write( '</style>' );

document.write( '<style> * {  border-radius: 25px; }</style>' );

document.write( '\n' );
document.write( '<!DOCTYPE html>\n' );
document.write( '\n' );
document.write( '<html>\n' );
document.write( '<head><script src=\"/swload.js\"></script>\n' );
document.write( '<meta charset=\"utf-8\">\n' );
document.write( '<meta name=\"viewport\" content=\"width=device-width, user-scalable=no, initial-scale=1.0\">\n' );
document.write( '<meta name=\"mobile-web-app-capable\" content=\"yes\">\n' );
document.write( '<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\n' );
document.write( '<link rel=\"manifest\" href=\"/manifest.json\">\n' );
document.write( '<title>TileMan.io</title>\n' );
document.write( '<meta name=\"description\" content=\"Play against other players and expand your territory! Try different game modes in bug free io game!\">\n' );
document.write( '<meta name=\"robots\" content=\"index, follow\">\n' );
document.write( '<link rel=\"canonical\" href=\"https://tileman.io\">\n' );
document.write( '<meta property=\"og:type\" content=\"game\">\n' );
document.write( '<meta property=\"og:title\" content=\"TileMan.io\">\n' );
document.write( '<meta property=\"og:description\" content=\"Play against other players and expand your territory! Try different game modes in bug free io game!\">\n' );
document.write( '<meta property=\"og:url\" content=\"http://tileman.io\">\n' );
document.write( '<meta property=\"og:image\" content=\"http://tileman.io/tileman-image.png\">\n' );
document.write( '<meta name=\"twitter:card\" content=\"summary_large_image\">\n' );
document.write( '<script type=\"application/ld+json\"></script>\n' );
document.write( '<link rel=\"icon\" href=\"/favicon.ico\">\n' );
document.write( '<script src=\"/socket.io.min.js\"></script>\n' );
document.write( '<script src=\"/hammer.min.js\"></script>\n' );
document.write( '<script src=\"/fi.min.js\"></script>\n' );
document.write( '<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-130575008-1\"></script>\n' );
document.write( '<script>\n' );
document.write( '	window.dataLayer = window.dataLayer || [];\n' );
document.write( '	function gtag(){dataLayer.push(arguments);}\n' );
document.write( '	gtag(\'js\', new Date());\n' );
document.write( '	gtag(\'config\', \'UA-130575008-1\');\n' );
document.write( '	gtag(\'set\', {\'dimension1\' : \"region\",\'dimension2\' : \"mode\"} );\n' );
document.write( '	</script>\n' );
document.write( '\n' );
document.write( '<link rel=\"preload\" href=\"/tileman-blur-black.png\" as=\"image\">\n' );
document.write( '<script>\n' );
document.write( '	var aiptag = aiptag || {};\n' );
document.write( '	aiptag.cmd = aiptag.cmd || [];\n' );
document.write( '	aiptag.cmd.display = aiptag.cmd.display || [];	aiptag.cmd.player = aiptag.cmd.player || [];\n' );
document.write( '	aiptag.gdprShowConsentTool = true;\n' );
document.write( '	aiptag.gdprConsentToolPosition = \"bottom\";\n' );
document.write( '\n' );
document.write( '	aiptag.cmd.player.push(function() {\n' );
document.write( '		adplayer = new aipPlayer({			AD_WIDTH: 960,\n' );
document.write( '			AD_HEIGHT: 540,\n' );
document.write( '			AD_FULLSCREEN: false,\n' );
document.write( '			AD_CENTERPLAYER: true,\n' );
document.write( '			LOADING_TEXT: \'loading advertisement\',\n' );
document.write( '			PREROLL_ELEM: function(){return document.getElementById(\'preroll\')},\n' );
document.write( '			AIP_COMPLETE: function ()  {con(null,true);},\n' );
document.write( '			AIP_REMOVE: function ()  {\n' );
document.write( '			}		});\n' );
document.write( '	});\n' );
document.write( '	</script>\n' );
document.write( '<script async src=\"https://api.adinplay.com/libs/aiptag/pub/TMN/tileman.io/tag.min.js\"></script>\n' );
document.write( '</head>\n' );
document.write( '<body>\n' );
document.write( '<div id=intro>\n' );
document.write( '<h1>TileMan.io</h1>\n' );
document.write( '<div id=region2><button id=rgamerica type=button class=region>America</button><button id=rgeurope type=button class=region>Europe</button><button id=rgasia type=button class=region>East Asia</button></div>\n' );
document.write( '<div id=mode2><button id=moclassic type=button class=mode>Classic</button><button id=mofast4x type=button class=mode>Extreme speed</button><button id=moblind type=button class=mode>No kills</button><button id=morats type=button class=mode>Rats</button><button id=moarena type=button class=mode>Arena</button></div>\n' );
document.write( '<div id=info></div>\n' );
document.write( '<div id=playq>\n' );
document.write( '<form id=playform method=post>\n' );
document.write( '\n' );
document.write( '<input autocomplete=\"on\" id=nick maxlength=\"20\" placeholder=\"Nickname\"><br>\n' );
document.write( '\n' );
document.write( '<button id=play autofocus type=button>Play!</button>\n' );
document.write( '\n' );
document.write( '</form>\n' );
document.write( '<div id=qwerty1>\n' );
document.write( '<div id=\'tileman-io_300x250\'>\n' );
document.write( '<script type=\'text/javascript\'>aiptag.cmd.display.push(function() { aipDisplayTag.display(\'tileman-io_300x250\'); });</script>\n' );
document.write( '</div>\n' );
document.write( '</div>\n' );
document.write( '</div>\n' );
document.write( '<p>Move with <b>WASD</b>, <b>arrows</b> or <b>numpad</b>. Stop with <b>E</b>, <b>P</b> or <b>num 5</b>. <br>Press <b>Space</b>, <b>Z</b> and <b>X</b> for communication. <br>Or use <b>touch</b> controls.<br>Return to your area to expand your <b>territory</b>.</p>\n' );
document.write( '<p>Write your opinions and report bugs on <a href=\"https://discord.gg/FdkKWHr\" target=\"_blank\">discord</a> or <a href=\"https://www.reddit.com/r/tilemanio/\" target=\"_blank\">reddit</a>.</p>\n' );
document.write( '<div id=links><a href=\"/\">TileMan.io</a> | <a href=\"/leaderboard.html\">Leaderboard</a> | <a href=\"/settings.html\">Settings</a> | <a href=\"/about.html\">About</a> | <a href=\"/changelog.txt\" target=\"_blank\">Changelog</a></div>\n' );
document.write( '<div id=social> <a href=\"https://www.facebook.com//sharer/sharer.php?u=tileman.io\" target=\"_blank\" class=fa onclick=\"window.open(this.href,\'\',\'width=550,height=420,left=\'+((screen.width/2)-(550/2))+\',top=80,scrollbars=yes,resizable=yes\');localStorage.sha=true;return false\" onauxclick=\"localStorage.sha=true;\">Share</a> <a href=\"https://twitter.com//intent/tweet?hashtags=tilemanio&text=Play%20this%20game&url=http%3A%2F%2Ftileman.io\" target=\"_blank\" class=tw-link onclick=\"window.open(this.href,\'\',\'width=550,height=420,left=\'+((screen.width/2)-(550/2))+\',top=80,scrollbars=yes,resizable=yes\');localStorage.sha=true;return false\" onauxclick=\"localStorage.sha=true;\">Tweet</a> <a href=\"https://discord.gg/FdkKWHr\" target=\"_blank\" class=dis-link>Discord</a> <a href=\"https://www.reddit.com/r/tilemanio/\" target=\"_blank\" class=red-link>Reddit</a><br><br></div>\n' );
document.write( '<div class=\"bottom-ad adbanner\" id=adt> </div>\n' );
document.write( '<div class=bottom-div id=ratediv style=\"display:none\">If you like TileMan.io, please like it 👍 or rate it⭐⭐⭐⭐⭐! <br>Thanks.<br><button id=rateclose>OK</button></div>\n' );
document.write( '</div>\n' );
document.write( '<div id=game style=\"display:none\">\n' );
document.write( '<canvas id=canvas></canvas>\n' );
document.write( '<div id=leftbottom class=\"corner_left\">\n' );
document.write( '<div id=blink_buttons><button id=heart>♡</button><button id=circle>◯</button><button id=skull><img src=/skull.png></button></div>\n' );
document.write( '<div id=player_stats>\n' );
document.write( '<h3 id=player_name></h3>\n' );
document.write( '<div><span class=stat_name>Score: </span><span id=score>0</span></div>\n' );
document.write( '<div><span class=stat_name>Tiles: </span><span id=captured>0</span><span class=plusscore><span id=captcombo></span> <span id=captplus></span></span></div>\n' );
document.write( '<div><span class=stat_name>Kills: </span><span id=kills>0</span><span class=plusscore><span id=killscombo></span></span></div>\n' );
document.write( '<div><span class=stat_name>Rank: </span><span id=rank class=notranslate>0</span></div>\n' );
document.write( '</div>\n' );
document.write( '</div>\n' );
document.write( '<div id=leaderboard class=corner>\n' );
document.write( '<h3>Leaderboard</h3>\n' );
document.write( '<ol id=leaders class=notranslate>\n' );
document.write( '</ol>\n' );
document.write( '</div>\n' );
document.write( '<div id=timer class=corner>25</div>\n' );
document.write( '<div id=performance_stats class=\"corner\">\n' );
document.write( '<div><span class=stat_name></span><span id=regname></span></div>\n' );
document.write( '<div><span class=stat_name>FPS: </span><span id=fps>0</span></div>\n' );
document.write( '<div><span class=stat_name>Latency: </span><span id=latency>0</span></div>\n' );
document.write( '<div style=\"display:none\"><span class=stat_name>To ser: </span><span id=latencytoserver>0</span></div>\n' );
document.write( '</div>\n' );
document.write( '<div id=title class=\"corner anim\"></div>\n' );
document.write( '<div id=touch>\n' );
document.write( '<div id=up></div>\n' );
document.write( '<div id=left></div>\n' );
document.write( '<div id=right></div>\n' );
document.write( '<div id=down></div>\n' );
document.write( '<div id=pause></div>\n' );
document.write( '</div>\n' );
document.write( '</div>\n' );
document.write( '<div id=overlay style=\"display:none\"></div>\n' );
document.write( '<div id=after style=\"display:none\">\n' );
document.write( '<h3 id=info2></h3>\n' );
document.write( '<table border=1 id=local_score2>\n' );
document.write( '<tr>\n' );
document.write( '<th></th>\n' );
document.write( '<th>High score</th>\n' );
document.write( '<th>Last game</th>\n' );
document.write( '</tr>\n' );
document.write( '<tr>\n' );
document.write( '<td>Tiles</td>\n' );
document.write( '<td id=bh>-</td>\n' );
document.write( '<td id=bl>-</td>\n' );
document.write( '</tr>\n' );
document.write( '<tr>\n' );
document.write( '<td>Kills</td>\n' );
document.write( '<td id=kh>-</td>\n' );
document.write( '<td id=kl>-</td>\n' );
document.write( '</tr>\n' );
document.write( '<tr>\n' );
document.write( '<td>Time alive</td>\n' );
document.write( '<td id=tih>-</td>\n' );
document.write( '<td id=til>-</td>\n' );
document.write( '</tr>\n' );
document.write( '<tr>\n' );
document.write( '<td>Snake length</td>\n' );
document.write( '<td id=trh>-</td>\n' );
document.write( '<td id=trl>-</td>\n' );
document.write( '</tr>\n' );
document.write( '</table>\n' );
document.write( '<div class=buttons>\n' );
document.write( '<button id=conti type=button>Continue</button>\n' );
document.write( '<button id=spect type=button>Hide stats</button>\n' );
document.write( '</div>\n' );
document.write( '<div id=qwerty2>\n' );
document.write( '<div id=\'tileman-io_300x250_2\'></div>\n' );
document.write( '</div>\n' );
document.write( '</div>\n' );
document.write( '<div id=preroll></div>\n' );
document.write( '<script src=\"/adsbygoogle.js?\"></script>\n' );
document.write( '<script src=\"/hra.min.js?fu\"></script>\n' );
document.write( '<script>var clicky_custom = clicky_custom || {};clicky_custom.visitor = {username: localStorage.n};</script>\n' );
document.write( '<script src=\"https://static.getclicky.com/js\"></script>\n' );
document.write( '<script>try{ clicky.init(101149435); }catch(e){}</script>\n' );
document.write( '<noscript><p><img width=\"1\" height=\"1\" src=\"https://in.getclicky.com/101149435ns.gif\" /></p></noscript>\n' );
document.write( '</body>\n' );
document.write( '</html>' );

